[WIP] Copy data modules and utility from Stoa
bpfkorea/boa-sdk-ts pull request #54
Opened 2020-11-23 09:21 UTC by MichaelKim20

I copied data modules and some utilities from Stoa into SDK.

2020-11-23 09:38 UTC, Geod24 commented
Yes, this is the way to go. And then we can make Stoa depends on this project and remove the duplication.

2020-11-25 10:29 UTC, Geod24 commented
The changes here are reverting https://github.com/bpfkorea/boa-sdk-ts/pull/53 which doesn't sound right.

2020-11-25 13:04 UTC, MichaelKim20 commented
> The changes here are reverting #53 which doesn't sound right.

The previous version was compiled into Node version 15.
And it doesn't match package.json.
I just installed Node version 15 and modified it to package-lock.json matching package.json.

2020-11-25 13:17 UTC, MichaelKim20 commented
> > The changes here are reverting #53 which doesn't sound right.
> 
> The previous version was compiled into Node version 15.
> And it doesn't match package.json.
> I just installed Node version 15 and modified it to package-lock.json matching package.json.
> I think it is problematic to commit only package-lock.json. From now on, we'd better commit with package.json.

I think it's because of the version difference.
Now we need to use Node version 15.3 or higher.

2020-11-25 14:36 UTC, Geod24 commented
> The previous version was compiled into Node version 15.
> And it doesn't match package.json.

Yep, that's what I feared, going to revert it then.

> I think it is problematic to commit only package-lock.json. From now on, we'd better commit with package.json.

I'm not sure what you mean.

2020-11-26 10:06 UTC, TrustHenry commented on src/modules/data/Height.ts
> +import {Utils} from "../..";
```suggestion
import { Utils } from "../..";
```

2020-11-26 10:25 UTC, Geod24 requested changes
Few fixes needed. Last commit seems like it can be removed.
Another English thing: You fix the document*ation*, not the document itself.

2020-11-26 10:25 UTC, Geod24 commented on src/modules/utils/Utils.ts
> +}
Why?
There is https://www.geeksforgeeks.org/node-js-buffer-writebiguint64le-method/
It's even used in Stoa.

2020-11-26 10:25 UTC, Geod24 commented on src/modules/data/KeyPair.ts
> +    }
Are those really needed ? It's only used to construct invalid object, which only seems to happen in tests that don't bother creating valid objects.

2020-11-26 10:25 UTC, Geod24 commented on tests/BOAClient.test.ts
> -            });
Thanks! 👍

2020-11-26 10:25 UTC, Geod24 commented on package-lock.json
> +  "lockfileVersion": 2,
So you originally reverted it, and I agree it was good. I went ahead and reverted the PR. Why are you re-adding it now ?

2020-11-26 10:45 UTC, MichaelKim20 commented
I tried to separate commit from this PR and make another PR, but you were already reviewing it, so I put it back.

2020-11-26 10:51 UTC, MichaelKim20 commented on package-lock.json
> +  "lockfileVersion": 2,
github CI on Linux, when Node is version 15
Modules that are not made of node version 15 cannot be auto-installed with a flag address.
So I had to set the node version to 15.
We created a new package-lock.json by deleting the package-lock.json that already exists and installing npm.
This is the only way to get through Stoa's CI.
And I installed node 15 on Linux and tested it or got the same result.

2020-11-26 10:56 UTC, MichaelKim20 commented on src/modules/utils/Utils.ts
> +}
SDK should also be used in the browser, but some browsers does not support 'writeBigUInt64LE'.

2020-11-26 11:06 UTC, MichaelKim20 commented on src/modules/data/Height.ts
> +import {Utils} from "../..";
I fixed it, Thank you for review

2020-11-26 11:09 UTC, TrustHenry approved these changes
LGTM. @Geod24  except for comments.

2020-11-27 00:34 UTC, MichaelKim20 commented on src/modules/data/KeyPair.ts
> +    }
You're right. Let's get rid of it and find another way.

2020-11-27 00:35 UTC, MichaelKim20 commented
> Few fixes needed. Last commit seems like it can be removed.
> Another English thing: You fix the document_ation_, not the document itself.

The last commit was removed.

2020-11-27 05:43 UTC, merged

2020-11-27 05:45 UTC, Geod24 commented
Urgh, I didn't realize the `package-lock.json` 10k LoC diff was still here... Can you guys please make sure your configurations are in sync so we stop this yoyo ?