Add a timestamp in  the block header
bpfkorea/boa-sdk-ts pull request #84
Opened 2021-01-08 06:05 UTC by TrustHenry

Synchronize Agora changes

https://github.com/bpfkorea/agora/pull/1437

2021-01-11 08:51 UTC, TrustHenry commented
ping

2021-01-12 01:52 UTC, MichaelKim20 commented
The following code needs to be modified:
``` DIFF

--- a/src/modules/utils/JSONValidator.ts
+++ b/src/modules/utils/JSONValidator.ts
@@ -102,6 +102,9 @@ export class JSONValidator
                         },
                         "type": "array"
                     },
+                    "timestamp": {
+                        "type": "string"
+                    }
                 },
                 "additionalProperties": false,
                 "required": [
@@ -110,7 +113,8 @@ export class JSONValidator
                     "merkle_root",
                     "validators",
                     "signature",
-                    "enrollments"
+                    "enrollments",
+                    "timestamp"
                 ]
             }
         ],

```

2021-01-12 01:56 UTC, TrustHenry commented
@MichaelKim20 Thanks for the review.  I apply the suggestion.

2021-01-12 02:34 UTC, MichaelKim20 approved these changes
It's very good for now. But I need to check if it is applied to Stoa and works properly so that it can be finally approved.

2021-01-12 02:37 UTC, MichaelKim20 requested changes

2021-01-12 02:37 UTC, MichaelKim20 commented on src/modules/utils/JSONValidator.ts
> +                        "type": "string"
```suggestion
                        "type": "number"
```

2021-01-12 02:38 UTC, MichaelKim20 commented on src/modules/utils/JSONValidator.ts
> +                        "type": "string"
{
  "prev_block": "0x8c1767e1c770ec82d597a01197eaccdcd04ff576a70c44beb73d14d98f9213e9b7c961ae22ce53c2dec51371f3331d847309280414b3a7967ebb217fe9fe94b3",
  "height": "9",
  "merkle_root": "0x6a0804c2f3cb3b0d64cd8cf2da34623ff43a0ccee1bd4be686d1ea3f3c3724f04e620acc0c2f2f02813c316607a81ac9963181b639e4b13cd53c04fcc2e18fbc",
  "validators": "[252]",
  "signature": "0x08842aff36b64eb13043f33416b07aad510bed53088024743746544061a646a540d334d2cdb3d745bd2ff2aedf6e10422bd6a8445e7df60d1ddc6158792379fc",
  "enrollments": [],
  "random_seed": "0x60d0e8ff49edc4c24756519dc2ed50c8195ec1847d415de413471bde04c93c3f268c071c22fd9b2dc7baae8c28c45c6bdd5fa74115e9fd6a1be37a324fa9e53f",
  "missing_validators": [],
  "timestamp": 1610418348
}

2021-01-12 02:55 UTC, MichaelKim20 commented on src/modules/utils/JSONValidator.ts
> +                        "type": "string"
``` TypeScript
        let a = new Date(4503599627370496);
        console.log(a.toDateString());
        let b = new Date(1610418348);
        console.log(b.toDateString());
```
Result : 
Thu May 24 144683
Tue Jan 20 1970

4503599627370496 is 2^52 (Number's Max)

So we can treat this as a Nuber.

2021-01-12 07:25 UTC, MichaelKim20 approved these changes

2021-01-12 07:25 UTC, merged